name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "fb2111240d944de5ba087942c37132fe" # action部署时被变量替换

[triggers]
crons = ["{CF_CRONS}"] # action部署时被变量替换，默认为北京时间 9:00 和 21:00
